[package]
name = "png"
version = "0.1.0"
authors = ["zakhar-kravtsov <zakhar.kravtsov@developex.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
debug = true